project:
  type: website
  execute-dir: file

website:
  title: "Jodie Wiggins | Data Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true